font_family      FiraCode Nerd Font
# font_family      Monaspace Neon Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 15.0

disable_ligatures never

tab_bar_edge top

mouse_hide_wait 0

copy_on_select no

strip_trailing_spaces never

select_by_word_characters @-./_~?&=%+#

repaint_delay 10
input_delay 3
sync_to_monitor yes

cursor_trail 0

# BEGIN_KITTY_THEME
# Default
include current-theme.conf
# END_KITTY_THEME

allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled

action_alias kitty_scrollback_nvim kitten ${HOME}/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
map kitty_mod+h kitty_scrollback_nvim --nvim-args -c 'set nospell'
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output --nvim-args -c 'set nospell'
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
