require('plugins.lazy')
require('plugins.telescope')
require('plugins.gitsigns')
require('plugins.neotree')

require('commands')
require('configs')
require('mappings')
require('lsp')
require('themes')
