[bar.default]
end = [ "tray", "clipboard", "temp", "privacy", "group:g1", "battery", "notifications", "session", "control-center" ]
margin_ends = 5
padding = 0
start = [ "launcher", "workspaces", "media" ]
thickness = 30
widget_spacing = 10

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "volume", "bluetooth", "brightness", "input_volume", "network" ]
    opacity = 1.0
    padding = 6.0

[battery]
warning_threshold = 25

[control_center]
width = 1000

[desktop_widgets]
enabled = false

[dock]
smart_auto_hide = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-2", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1197.3333740234375
    output = "HDMI-A-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 1018.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]

[shell]
screen_time_enabled = true

    [shell.panel]
    open_near_click_control_center = true

[theme]
builtin = "Kanagawa"
community_palette = "Ayu Blue"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

[wallpaper.default]
path = "/home/an/Pictures/Wallpapers/lakeside/0.jpg"

[wallpaper.last]
path = "/home/an/Pictures/Wallpapers/lakeside/0.jpg"

[wallpaper.monitors.HDMI-A-2]
path = "/home/an/Pictures/Wallpapers/forest/0.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/an/Pictures/Wallpapers/lakeside/0.jpg"

[widget.clock]
format = "{:%a %d %b - %H:%M}"

[widget.privacy]
hide_inactive = true

[widget.sysmon]
stat = "gpu_usage"
